from typing import List, Dict

class TDScriptGenerator:
    """Generates TD Battle Pet Scripts from simulation logs"""
    
    @staticmethod
    def generate_script(events: List[Dict]) -> str:
        lines = []
        last_turn = -1
        
        # Header
        lines.append("// Generated by PetWeaver AI")
        
        for event in events:
            # Filter for Player actions only
            if event.get('actor') != 'player':
                continue
                
            turn = event.get('turn')
            if turn == last_turn: 
                continue # Already recorded action for this turn
            
            last_turn = turn
            
            if event['type'] in ['damage', 'heal', 'miss', 'immunity_block']:
                # Player used an ability
                ability_name = event.get('ability', 'Unknown')
                # TD Script format: use(Ability Name) [round=X]
                lines.append(f"use({ability_name}) [round={turn}]")
                
            elif event['type'] == 'swap':
                # Player swapped pets
                # Simulator uses 0-based index, TD uses 1-based (#1, #2, #3)
                new_slot = event.get('new_index', 0) + 1
                lines.append(f"change(#{new_slot}) [round={turn}]")
        
        # Add a catch-all at the end to prevent stalling
        lines.append("use(1)") 
        
        return "\n".join(lines)
